### ISSUE TITLE
Performance issue with the OnUpdate mehod

### ISSUE THREAD

**Issue by sipertruk** [vallantv/MBBClassic#13]
There are addons that attach hundreds of children to the Minimap frame.
Therefore by iterating those MBB_OnUpdate is causing a small frame lag every 3 seconds that gets annoying because the textures flicker.
If I change MBB_OnUpdate  to only do that iterating once the problem is gone with no apparent side effect at least on my setup.

**Comment by vallantv** [comment]
Go ahead and make a pull request and I'll merge it

**Comment by vallantv** [comment]
Can you give me a list of addons that you are using? Maybe we're just missing an exclusion from the list and we don't need to make this code change. 

Thanks,
Ron

**Comment by sipertruk** [comment]
Questie is creating 751 frames named QuestieFrameX.
Anyway is there any addon out there that creates a minimap button post launch that would require iterating the children on every update ? I mean something not the consequence of just a setting change that would be fixed by a /reload. On the fly button creation caused by a random event ..

**Comment by sipertruk** [comment]
QuestieFrame is already in the exclude list by the way so the frame lag is caused by whatever is done before the check.

**Comment by vallantv** [comment]
Merged. Thanks! Would you like to be added as an author/collaborator on the github and curseforge? I really don't have a lot of time to work on this stuff, I was just trying to keep it alive because I love the addon.
