### ISSUE TITLE
Overwriting minimap button click registration breaks some addons

### ISSUE THREAD

**Issue by Road-block** [vallantv/MBBClassic#19]
There are addons that have functionality attached to their minimap buttons that extends beyond the left/right click (a bunch of LDB launchers or feeds for example)

This line [MBB.lua:342](https://github.com/vallantv/MBBClassic/blob/e4f48101105c8fa0dea021b93bb7cc7c3f877877/MBB.lua#L342) breaks them.
I haven't checked the retail version but I'm assuming the same happens there.

If for some reason replacing the click registration is needed at least do this instead.

```lua
buttonframe:RegisterForClicks("AnyDown")
```
so middle / btn4 or btn5 clicks are not ignored.

**Comment by vallantv** [comment]
Thanks for the report. I don’t have wow installed atm. I’d happily merge this change if you’d like to make a Pull request. Cheers, Vall.
