### ISSUE TITLE
Framerate drop in Classic

### ISSUE THREAD

**Issue by vallantv** [vallantv/MBBClassic#3]
> Been using this in Classic as my minimap was looking like a dogs breakfast
> 
>  
> 
> As of today, when standing still i have no issues, but when moving my framerate drops from 100 to 10 or lower.
> 
>  
> 
> Disabling MBB leaves my framerate at a consistent 100
> 
>  
> 
> :(

**Comment by Jh16** [comment]
Has something to do with the collapsing of the buttons. My game always goes not responsive after it collapses.

**Comment by vallantv** [comment]
I'll test that, thanks for the feedback.
