### ISSUE TITLE
Button Collapse - Lag Spike

### ISSUE THREAD

**Issue by Jh16** [vallantv/MBBClassic#7]
When collapsing it causes a major lag spike and sometimes causes WoW classic to go not responsive.

**Comment by vallantv** [comment]
We think this was related to gatherlite are you using that addon?

**Comment by Jh16** [comment]
Last time I used GatherLite was within the first two months of Classic release. Then I switched to GatherMate 2 and have been using it ever since. :/

**Comment by vallantv** [comment]
Can you list your addons? Are you using Nauticus?

**Comment by Jh16** [comment]
Umm, I've got quite a bit. NauticusClassic is one of them correct.

**Comment by vallantv** [comment]
I just pushed a fix for nauticus. It should be available on twitch soon

**Comment by Jh16** [comment]
Aight, I'll keep my eye on the Twitch app :)
